import os


CLOUDFLARE_API_KEY = ""
CLOUDFLARE_ACCOUNT_ID = ""
OPENAI_API_KEY = "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"
